from ml.engine import Part, Port
from ml.strategies import all_updated
from me.domains.hardware.digital import Logic, rising_edge, generate_code
import os
import sys

class Counter(Part):
    """
    A simple up-counter that toggles the output bit based on the internal count.
    """
    def __init__(self, identifier: str):
        ports = [
            Port('clk', Port.IN, type=Logic),
            Port('rst', Port.IN, type=Logic),
            Port('out_0', Port.OUT, type=Logic)
        ]
        super().__init__(identifier=identifier, ports=ports, scheduling_condition=all_updated, scheduling_args=('clk',))
        self.cnt = 0

    @rising_edge('clk')
    def behavior(self):
        if self.get_port('rst').get() == Logic.ONE:
            self.cnt = 0
        else:
            self.cnt = self.cnt + 1
        
        # Output Logic.ONE if count is odd, else Logic.ZERO
        if (self.cnt % 2) != 0:
            self.get_port('out_0').set(Logic.ONE)
        else:
            self.get_port('out_0').set(Logic.ZERO)

def generate_vhdl_code():
    try:
        from google import genai
        from google.genai import errors
    except ImportError:
        print("Error: 'google-genai' library not found. Please run: pip install google-genai")
        return
    
    import time

    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("Error: GEMINI_API_KEY environment variable is not set.")
        return

    client = genai.Client(api_key=api_key)
    model="gemini-2.5-flash-lite"

    def gemini_client(prompt: str) -> str:
        retries = 3
        while retries > 0:
            try:
                response = client.models.generate_content(model=model, contents=prompt)
                text = response.text.replace("```vhdl", "").replace("```", "").strip()
                return f"-- Generated by {model}\n{text}"
            except errors.ClientError as e:
                if e.code == 429:
                    print("Quota exceeded (429). Retrying in 35 seconds...")
                    time.sleep(35)
                    retries -= 1
                elif e.code == 404:
                    print(f"Error: Model '{model}' not found.")
                    sys.exit(0)
                else:
                    raise e
        raise Exception("Gemini API quota exceeded after retries.")

    try:
        vhdl_code = generate_code(Counter('dut'), language="VHDL", entity_name="counter", architecture_name="rtl", llm_client=gemini_client)
    except Exception as e:
        raise Exception(f"VHDL generation failed: {e}")

    output_dir = "gen"
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    filename = os.path.join(output_dir, "counter.vhd")
    with open(filename, "w") as f:
        f.write(vhdl_code)
    print(f"VHDL code generated in {filename}")

if __name__ == "__main__":
    generate_vhdl_code()